<?php
/**
 * RoleElevationApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`.
 *
 * The version of the OpenAPI document: 1.3.10
 * Contact: support@mudbase.dev
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * RoleElevationApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RoleElevationApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'approveRoleElevation' => [
            'application/json',
        ],
        'getPendingRoleElevationRequests' => [
            'application/json',
        ],
        'getRoleElevationStatus' => [
            'application/json',
        ],
        'requestRoleElevation' => [
            'application/json',
        ],
        'uploadVerificationDocuments' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation approveRoleElevation
     *
     * Approve/reject role elevation request (admin only)
     *
     * @param  string $org_id org_id (required)
     * @param  string $request_id request_id (required)
     * @param  \OpenAPI\Client\Model\ApproveRoleElevationRequest $approve_role_elevation_request approve_role_elevation_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['approveRoleElevation'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\ApproveRoleElevation200Response
     */
    public function approveRoleElevation($org_id, $request_id, $approve_role_elevation_request, string $contentType = self::contentTypes['approveRoleElevation'][0])
    {
        list($response) = $this->approveRoleElevationWithHttpInfo($org_id, $request_id, $approve_role_elevation_request, $contentType);
        return $response;
    }

    /**
     * Operation approveRoleElevationWithHttpInfo
     *
     * Approve/reject role elevation request (admin only)
     *
     * @param  string $org_id (required)
     * @param  string $request_id (required)
     * @param  \OpenAPI\Client\Model\ApproveRoleElevationRequest $approve_role_elevation_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['approveRoleElevation'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\ApproveRoleElevation200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function approveRoleElevationWithHttpInfo($org_id, $request_id, $approve_role_elevation_request, string $contentType = self::contentTypes['approveRoleElevation'][0])
    {
        $request = $this->approveRoleElevationRequest($org_id, $request_id, $approve_role_elevation_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ApproveRoleElevation200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\ApproveRoleElevation200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ApproveRoleElevation200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation approveRoleElevationAsync
     *
     * Approve/reject role elevation request (admin only)
     *
     * @param  string $org_id (required)
     * @param  string $request_id (required)
     * @param  \OpenAPI\Client\Model\ApproveRoleElevationRequest $approve_role_elevation_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['approveRoleElevation'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function approveRoleElevationAsync($org_id, $request_id, $approve_role_elevation_request, string $contentType = self::contentTypes['approveRoleElevation'][0])
    {
        return $this->approveRoleElevationAsyncWithHttpInfo($org_id, $request_id, $approve_role_elevation_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation approveRoleElevationAsyncWithHttpInfo
     *
     * Approve/reject role elevation request (admin only)
     *
     * @param  string $org_id (required)
     * @param  string $request_id (required)
     * @param  \OpenAPI\Client\Model\ApproveRoleElevationRequest $approve_role_elevation_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['approveRoleElevation'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function approveRoleElevationAsyncWithHttpInfo($org_id, $request_id, $approve_role_elevation_request, string $contentType = self::contentTypes['approveRoleElevation'][0])
    {
        $returnType = '\OpenAPI\Client\Model\ApproveRoleElevation200Response';
        $request = $this->approveRoleElevationRequest($org_id, $request_id, $approve_role_elevation_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'approveRoleElevation'
     *
     * @param  string $org_id (required)
     * @param  string $request_id (required)
     * @param  \OpenAPI\Client\Model\ApproveRoleElevationRequest $approve_role_elevation_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['approveRoleElevation'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function approveRoleElevationRequest($org_id, $request_id, $approve_role_elevation_request, string $contentType = self::contentTypes['approveRoleElevation'][0])
    {

        // verify the required parameter 'org_id' is set
        if ($org_id === null || (is_array($org_id) && count($org_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_id when calling approveRoleElevation'
            );
        }

        // verify the required parameter 'request_id' is set
        if ($request_id === null || (is_array($request_id) && count($request_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $request_id when calling approveRoleElevation'
            );
        }

        // verify the required parameter 'approve_role_elevation_request' is set
        if ($approve_role_elevation_request === null || (is_array($approve_role_elevation_request) && count($approve_role_elevation_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $approve_role_elevation_request when calling approveRoleElevation'
            );
        }


        $resourcePath = '/api/orgs/{orgId}/role-elevation/{requestId}/approve';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($org_id !== null) {
            $resourcePath = str_replace(
                '{' . 'orgId' . '}',
                ObjectSerializer::toPathValue($org_id),
                $resourcePath
            );
        }
        // path params
        if ($request_id !== null) {
            $resourcePath = str_replace(
                '{' . 'requestId' . '}',
                ObjectSerializer::toPathValue($request_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($approve_role_elevation_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($approve_role_elevation_request));
            } else {
                $httpBody = $approve_role_elevation_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getPendingRoleElevationRequests
     *
     * Get pending role elevation requests (admin only)
     *
     * @param  string $org_id org_id (required)
     * @param  string|null $status status (optional, default to 'pending')
     * @param  int|null $page page (optional, default to 1)
     * @param  int|null $limit limit (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPendingRoleElevationRequests'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\GetPendingRoleElevationRequests200Response
     */
    public function getPendingRoleElevationRequests($org_id, $status = 'pending', $page = 1, $limit = 50, string $contentType = self::contentTypes['getPendingRoleElevationRequests'][0])
    {
        list($response) = $this->getPendingRoleElevationRequestsWithHttpInfo($org_id, $status, $page, $limit, $contentType);
        return $response;
    }

    /**
     * Operation getPendingRoleElevationRequestsWithHttpInfo
     *
     * Get pending role elevation requests (admin only)
     *
     * @param  string $org_id (required)
     * @param  string|null $status (optional, default to 'pending')
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPendingRoleElevationRequests'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\GetPendingRoleElevationRequests200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPendingRoleElevationRequestsWithHttpInfo($org_id, $status = 'pending', $page = 1, $limit = 50, string $contentType = self::contentTypes['getPendingRoleElevationRequests'][0])
    {
        $request = $this->getPendingRoleElevationRequestsRequest($org_id, $status, $page, $limit, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\GetPendingRoleElevationRequests200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\GetPendingRoleElevationRequests200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetPendingRoleElevationRequests200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getPendingRoleElevationRequestsAsync
     *
     * Get pending role elevation requests (admin only)
     *
     * @param  string $org_id (required)
     * @param  string|null $status (optional, default to 'pending')
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPendingRoleElevationRequests'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPendingRoleElevationRequestsAsync($org_id, $status = 'pending', $page = 1, $limit = 50, string $contentType = self::contentTypes['getPendingRoleElevationRequests'][0])
    {
        return $this->getPendingRoleElevationRequestsAsyncWithHttpInfo($org_id, $status, $page, $limit, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPendingRoleElevationRequestsAsyncWithHttpInfo
     *
     * Get pending role elevation requests (admin only)
     *
     * @param  string $org_id (required)
     * @param  string|null $status (optional, default to 'pending')
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPendingRoleElevationRequests'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPendingRoleElevationRequestsAsyncWithHttpInfo($org_id, $status = 'pending', $page = 1, $limit = 50, string $contentType = self::contentTypes['getPendingRoleElevationRequests'][0])
    {
        $returnType = '\OpenAPI\Client\Model\GetPendingRoleElevationRequests200Response';
        $request = $this->getPendingRoleElevationRequestsRequest($org_id, $status, $page, $limit, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPendingRoleElevationRequests'
     *
     * @param  string $org_id (required)
     * @param  string|null $status (optional, default to 'pending')
     * @param  int|null $page (optional, default to 1)
     * @param  int|null $limit (optional, default to 50)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPendingRoleElevationRequests'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getPendingRoleElevationRequestsRequest($org_id, $status = 'pending', $page = 1, $limit = 50, string $contentType = self::contentTypes['getPendingRoleElevationRequests'][0])
    {

        // verify the required parameter 'org_id' is set
        if ($org_id === null || (is_array($org_id) && count($org_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_id when calling getPendingRoleElevationRequests'
            );
        }





        $resourcePath = '/api/orgs/{orgId}/role-elevation/pending';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $status,
            'status', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($org_id !== null) {
            $resourcePath = str_replace(
                '{' . 'orgId' . '}',
                ObjectSerializer::toPathValue($org_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getRoleElevationStatus
     *
     * Get role elevation status
     *
     * @param  string $project_id project_id (required)
     * @param  string|null $role_slug role_slug (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRoleElevationStatus'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\GetRoleElevationStatus200Response
     */
    public function getRoleElevationStatus($project_id, $role_slug = null, string $contentType = self::contentTypes['getRoleElevationStatus'][0])
    {
        list($response) = $this->getRoleElevationStatusWithHttpInfo($project_id, $role_slug, $contentType);
        return $response;
    }

    /**
     * Operation getRoleElevationStatusWithHttpInfo
     *
     * Get role elevation status
     *
     * @param  string $project_id (required)
     * @param  string|null $role_slug (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRoleElevationStatus'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\GetRoleElevationStatus200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getRoleElevationStatusWithHttpInfo($project_id, $role_slug = null, string $contentType = self::contentTypes['getRoleElevationStatus'][0])
    {
        $request = $this->getRoleElevationStatusRequest($project_id, $role_slug, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\GetRoleElevationStatus200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\GetRoleElevationStatus200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetRoleElevationStatus200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getRoleElevationStatusAsync
     *
     * Get role elevation status
     *
     * @param  string $project_id (required)
     * @param  string|null $role_slug (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRoleElevationStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRoleElevationStatusAsync($project_id, $role_slug = null, string $contentType = self::contentTypes['getRoleElevationStatus'][0])
    {
        return $this->getRoleElevationStatusAsyncWithHttpInfo($project_id, $role_slug, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getRoleElevationStatusAsyncWithHttpInfo
     *
     * Get role elevation status
     *
     * @param  string $project_id (required)
     * @param  string|null $role_slug (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRoleElevationStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getRoleElevationStatusAsyncWithHttpInfo($project_id, $role_slug = null, string $contentType = self::contentTypes['getRoleElevationStatus'][0])
    {
        $returnType = '\OpenAPI\Client\Model\GetRoleElevationStatus200Response';
        $request = $this->getRoleElevationStatusRequest($project_id, $role_slug, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getRoleElevationStatus'
     *
     * @param  string $project_id (required)
     * @param  string|null $role_slug (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getRoleElevationStatus'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getRoleElevationStatusRequest($project_id, $role_slug = null, string $contentType = self::contentTypes['getRoleElevationStatus'][0])
    {

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling getRoleElevationStatus'
            );
        }



        $resourcePath = '/api/projects/{projectId}/role-elevation/status';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $role_slug,
            'roleSlug', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{' . 'projectId' . '}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation requestRoleElevation
     *
     * Request role elevation
     *
     * @param  string $project_id project_id (required)
     * @param  \OpenAPI\Client\Model\RequestRoleElevationRequest $request_role_elevation_request request_role_elevation_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['requestRoleElevation'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\RequestRoleElevation200Response
     */
    public function requestRoleElevation($project_id, $request_role_elevation_request, string $contentType = self::contentTypes['requestRoleElevation'][0])
    {
        list($response) = $this->requestRoleElevationWithHttpInfo($project_id, $request_role_elevation_request, $contentType);
        return $response;
    }

    /**
     * Operation requestRoleElevationWithHttpInfo
     *
     * Request role elevation
     *
     * @param  string $project_id (required)
     * @param  \OpenAPI\Client\Model\RequestRoleElevationRequest $request_role_elevation_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['requestRoleElevation'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\RequestRoleElevation200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function requestRoleElevationWithHttpInfo($project_id, $request_role_elevation_request, string $contentType = self::contentTypes['requestRoleElevation'][0])
    {
        $request = $this->requestRoleElevationRequest($project_id, $request_role_elevation_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\RequestRoleElevation200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\RequestRoleElevation200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\RequestRoleElevation200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation requestRoleElevationAsync
     *
     * Request role elevation
     *
     * @param  string $project_id (required)
     * @param  \OpenAPI\Client\Model\RequestRoleElevationRequest $request_role_elevation_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['requestRoleElevation'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function requestRoleElevationAsync($project_id, $request_role_elevation_request, string $contentType = self::contentTypes['requestRoleElevation'][0])
    {
        return $this->requestRoleElevationAsyncWithHttpInfo($project_id, $request_role_elevation_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation requestRoleElevationAsyncWithHttpInfo
     *
     * Request role elevation
     *
     * @param  string $project_id (required)
     * @param  \OpenAPI\Client\Model\RequestRoleElevationRequest $request_role_elevation_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['requestRoleElevation'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function requestRoleElevationAsyncWithHttpInfo($project_id, $request_role_elevation_request, string $contentType = self::contentTypes['requestRoleElevation'][0])
    {
        $returnType = '\OpenAPI\Client\Model\RequestRoleElevation200Response';
        $request = $this->requestRoleElevationRequest($project_id, $request_role_elevation_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'requestRoleElevation'
     *
     * @param  string $project_id (required)
     * @param  \OpenAPI\Client\Model\RequestRoleElevationRequest $request_role_elevation_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['requestRoleElevation'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function requestRoleElevationRequest($project_id, $request_role_elevation_request, string $contentType = self::contentTypes['requestRoleElevation'][0])
    {

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling requestRoleElevation'
            );
        }

        // verify the required parameter 'request_role_elevation_request' is set
        if ($request_role_elevation_request === null || (is_array($request_role_elevation_request) && count($request_role_elevation_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $request_role_elevation_request when calling requestRoleElevation'
            );
        }


        $resourcePath = '/api/projects/{projectId}/role-elevation/request';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{' . 'projectId' . '}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($request_role_elevation_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($request_role_elevation_request));
            } else {
                $httpBody = $request_role_elevation_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation uploadVerificationDocuments
     *
     * Upload verification documents
     *
     * @param  string $project_id project_id (required)
     * @param  \OpenAPI\Client\Model\UploadVerificationDocumentsRequest $upload_verification_documents_request upload_verification_documents_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['uploadVerificationDocuments'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function uploadVerificationDocuments($project_id, $upload_verification_documents_request, string $contentType = self::contentTypes['uploadVerificationDocuments'][0])
    {
        $this->uploadVerificationDocumentsWithHttpInfo($project_id, $upload_verification_documents_request, $contentType);
    }

    /**
     * Operation uploadVerificationDocumentsWithHttpInfo
     *
     * Upload verification documents
     *
     * @param  string $project_id (required)
     * @param  \OpenAPI\Client\Model\UploadVerificationDocumentsRequest $upload_verification_documents_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['uploadVerificationDocuments'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function uploadVerificationDocumentsWithHttpInfo($project_id, $upload_verification_documents_request, string $contentType = self::contentTypes['uploadVerificationDocuments'][0])
    {
        $request = $this->uploadVerificationDocumentsRequest($project_id, $upload_verification_documents_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation uploadVerificationDocumentsAsync
     *
     * Upload verification documents
     *
     * @param  string $project_id (required)
     * @param  \OpenAPI\Client\Model\UploadVerificationDocumentsRequest $upload_verification_documents_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['uploadVerificationDocuments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function uploadVerificationDocumentsAsync($project_id, $upload_verification_documents_request, string $contentType = self::contentTypes['uploadVerificationDocuments'][0])
    {
        return $this->uploadVerificationDocumentsAsyncWithHttpInfo($project_id, $upload_verification_documents_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation uploadVerificationDocumentsAsyncWithHttpInfo
     *
     * Upload verification documents
     *
     * @param  string $project_id (required)
     * @param  \OpenAPI\Client\Model\UploadVerificationDocumentsRequest $upload_verification_documents_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['uploadVerificationDocuments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function uploadVerificationDocumentsAsyncWithHttpInfo($project_id, $upload_verification_documents_request, string $contentType = self::contentTypes['uploadVerificationDocuments'][0])
    {
        $returnType = '';
        $request = $this->uploadVerificationDocumentsRequest($project_id, $upload_verification_documents_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'uploadVerificationDocuments'
     *
     * @param  string $project_id (required)
     * @param  \OpenAPI\Client\Model\UploadVerificationDocumentsRequest $upload_verification_documents_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['uploadVerificationDocuments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function uploadVerificationDocumentsRequest($project_id, $upload_verification_documents_request, string $contentType = self::contentTypes['uploadVerificationDocuments'][0])
    {

        // verify the required parameter 'project_id' is set
        if ($project_id === null || (is_array($project_id) && count($project_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $project_id when calling uploadVerificationDocuments'
            );
        }

        // verify the required parameter 'upload_verification_documents_request' is set
        if ($upload_verification_documents_request === null || (is_array($upload_verification_documents_request) && count($upload_verification_documents_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $upload_verification_documents_request when calling uploadVerificationDocuments'
            );
        }


        $resourcePath = '/api/projects/{projectId}/role-elevation/documents';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($project_id !== null) {
            $resourcePath = str_replace(
                '{' . 'projectId' . '}',
                ObjectSerializer::toPathValue($project_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($upload_verification_documents_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($upload_verification_documents_request));
            } else {
                $httpBody = $upload_verification_documents_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }
        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
