<?php
/**
 * AdminPlatformDnsVerificationPatchRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`.
 *
 * The version of the OpenAPI document: 1.3.12
 * Contact: support@mudbase.dev
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AdminPlatformDnsVerificationPatchRequest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AdminPlatformDnsVerificationPatchRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AdminPlatformDnsVerificationPatchRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'record_type' => 'string',
        'record_name' => 'string',
        'record_value' => 'string',
        'ttl_seconds' => 'int',
        'staff_note' => 'string',
        'reset_customer_platform_dns_submission' => 'bool',
        'notify_org' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'record_type' => null,
        'record_name' => null,
        'record_value' => null,
        'ttl_seconds' => null,
        'staff_note' => null,
        'reset_customer_platform_dns_submission' => null,
        'notify_org' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'record_type' => false,
        'record_name' => false,
        'record_value' => false,
        'ttl_seconds' => true,
        'staff_note' => true,
        'reset_customer_platform_dns_submission' => false,
        'notify_org' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'record_type' => 'recordType',
        'record_name' => 'recordName',
        'record_value' => 'recordValue',
        'ttl_seconds' => 'ttlSeconds',
        'staff_note' => 'staffNote',
        'reset_customer_platform_dns_submission' => 'resetCustomerPlatformDnsSubmission',
        'notify_org' => 'notifyOrg'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'record_type' => 'setRecordType',
        'record_name' => 'setRecordName',
        'record_value' => 'setRecordValue',
        'ttl_seconds' => 'setTtlSeconds',
        'staff_note' => 'setStaffNote',
        'reset_customer_platform_dns_submission' => 'setResetCustomerPlatformDnsSubmission',
        'notify_org' => 'setNotifyOrg'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'record_type' => 'getRecordType',
        'record_name' => 'getRecordName',
        'record_value' => 'getRecordValue',
        'ttl_seconds' => 'getTtlSeconds',
        'staff_note' => 'getStaffNote',
        'reset_customer_platform_dns_submission' => 'getResetCustomerPlatformDnsSubmission',
        'notify_org' => 'getNotifyOrg'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('record_type', $data ?? [], null);
        $this->setIfExists('record_name', $data ?? [], null);
        $this->setIfExists('record_value', $data ?? [], null);
        $this->setIfExists('ttl_seconds', $data ?? [], null);
        $this->setIfExists('staff_note', $data ?? [], null);
        $this->setIfExists('reset_customer_platform_dns_submission', $data ?? [], null);
        $this->setIfExists('notify_org', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['record_type']) && (mb_strlen($this->container['record_type']) > 32)) {
            $invalidProperties[] = "invalid value for 'record_type', the character length must be smaller than or equal to 32.";
        }

        if ($this->container['record_name'] === null) {
            $invalidProperties[] = "'record_name' can't be null";
        }
        if ((mb_strlen($this->container['record_name']) > 512)) {
            $invalidProperties[] = "invalid value for 'record_name', the character length must be smaller than or equal to 512.";
        }

        if ($this->container['record_value'] === null) {
            $invalidProperties[] = "'record_value' can't be null";
        }
        if ((mb_strlen($this->container['record_value']) > 4096)) {
            $invalidProperties[] = "invalid value for 'record_value', the character length must be smaller than or equal to 4096.";
        }

        if (!is_null($this->container['ttl_seconds']) && ($this->container['ttl_seconds'] > 86400)) {
            $invalidProperties[] = "invalid value for 'ttl_seconds', must be smaller than or equal to 86400.";
        }

        if (!is_null($this->container['ttl_seconds']) && ($this->container['ttl_seconds'] < 0)) {
            $invalidProperties[] = "invalid value for 'ttl_seconds', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['staff_note']) && (mb_strlen($this->container['staff_note']) > 4000)) {
            $invalidProperties[] = "invalid value for 'staff_note', the character length must be smaller than or equal to 4000.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets record_type
     *
     * @return string|null
     */
    public function getRecordType()
    {
        return $this->container['record_type'];
    }

    /**
     * Sets record_type
     *
     * @param string|null $record_type record_type
     *
     * @return self
     */
    public function setRecordType($record_type)
    {
        if (is_null($record_type)) {
            throw new \InvalidArgumentException('non-nullable record_type cannot be null');
        }
        if ((mb_strlen($record_type) > 32)) {
            throw new \InvalidArgumentException('invalid length for $record_type when calling AdminPlatformDnsVerificationPatchRequest., must be smaller than or equal to 32.');
        }

        $this->container['record_type'] = $record_type;

        return $this;
    }

    /**
     * Gets record_name
     *
     * @return string
     */
    public function getRecordName()
    {
        return $this->container['record_name'];
    }

    /**
     * Sets record_name
     *
     * @param string $record_name record_name
     *
     * @return self
     */
    public function setRecordName($record_name)
    {
        if (is_null($record_name)) {
            throw new \InvalidArgumentException('non-nullable record_name cannot be null');
        }
        if ((mb_strlen($record_name) > 512)) {
            throw new \InvalidArgumentException('invalid length for $record_name when calling AdminPlatformDnsVerificationPatchRequest., must be smaller than or equal to 512.');
        }

        $this->container['record_name'] = $record_name;

        return $this;
    }

    /**
     * Gets record_value
     *
     * @return string
     */
    public function getRecordValue()
    {
        return $this->container['record_value'];
    }

    /**
     * Sets record_value
     *
     * @param string $record_value record_value
     *
     * @return self
     */
    public function setRecordValue($record_value)
    {
        if (is_null($record_value)) {
            throw new \InvalidArgumentException('non-nullable record_value cannot be null');
        }
        if ((mb_strlen($record_value) > 4096)) {
            throw new \InvalidArgumentException('invalid length for $record_value when calling AdminPlatformDnsVerificationPatchRequest., must be smaller than or equal to 4096.');
        }

        $this->container['record_value'] = $record_value;

        return $this;
    }

    /**
     * Gets ttl_seconds
     *
     * @return int|null
     */
    public function getTtlSeconds()
    {
        return $this->container['ttl_seconds'];
    }

    /**
     * Sets ttl_seconds
     *
     * @param int|null $ttl_seconds ttl_seconds
     *
     * @return self
     */
    public function setTtlSeconds($ttl_seconds)
    {
        if (is_null($ttl_seconds)) {
            array_push($this->openAPINullablesSetToNull, 'ttl_seconds');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ttl_seconds', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($ttl_seconds) && ($ttl_seconds > 86400)) {
            throw new \InvalidArgumentException('invalid value for $ttl_seconds when calling AdminPlatformDnsVerificationPatchRequest., must be smaller than or equal to 86400.');
        }
        if (!is_null($ttl_seconds) && ($ttl_seconds < 0)) {
            throw new \InvalidArgumentException('invalid value for $ttl_seconds when calling AdminPlatformDnsVerificationPatchRequest., must be bigger than or equal to 0.');
        }

        $this->container['ttl_seconds'] = $ttl_seconds;

        return $this;
    }

    /**
     * Gets staff_note
     *
     * @return string|null
     */
    public function getStaffNote()
    {
        return $this->container['staff_note'];
    }

    /**
     * Sets staff_note
     *
     * @param string|null $staff_note staff_note
     *
     * @return self
     */
    public function setStaffNote($staff_note)
    {
        if (is_null($staff_note)) {
            array_push($this->openAPINullablesSetToNull, 'staff_note');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('staff_note', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($staff_note) && (mb_strlen($staff_note) > 4000)) {
            throw new \InvalidArgumentException('invalid length for $staff_note when calling AdminPlatformDnsVerificationPatchRequest., must be smaller than or equal to 4000.');
        }

        $this->container['staff_note'] = $staff_note;

        return $this;
    }

    /**
     * Gets reset_customer_platform_dns_submission
     *
     * @return bool|null
     */
    public function getResetCustomerPlatformDnsSubmission()
    {
        return $this->container['reset_customer_platform_dns_submission'];
    }

    /**
     * Sets reset_customer_platform_dns_submission
     *
     * @param bool|null $reset_customer_platform_dns_submission reset_customer_platform_dns_submission
     *
     * @return self
     */
    public function setResetCustomerPlatformDnsSubmission($reset_customer_platform_dns_submission)
    {
        if (is_null($reset_customer_platform_dns_submission)) {
            throw new \InvalidArgumentException('non-nullable reset_customer_platform_dns_submission cannot be null');
        }
        $this->container['reset_customer_platform_dns_submission'] = $reset_customer_platform_dns_submission;

        return $this;
    }

    /**
     * Gets notify_org
     *
     * @return bool|null
     */
    public function getNotifyOrg()
    {
        return $this->container['notify_org'];
    }

    /**
     * Sets notify_org
     *
     * @param bool|null $notify_org When not false (default), email org billing contact with step-3 DNS instructions after save.
     *
     * @return self
     */
    public function setNotifyOrg($notify_org)
    {
        if (is_null($notify_org)) {
            throw new \InvalidArgumentException('non-nullable notify_org cannot be null');
        }
        $this->container['notify_org'] = $notify_org;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


