<?php
/**
 * CalculateWalletFee200ResponseData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`.
 *
 * The version of the OpenAPI document: 1.3.3
 * Contact: support@mudbase.dev
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CalculateWalletFee200ResponseData Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CalculateWalletFee200ResponseData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'calculateWalletFee_200_response_data';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'currency' => 'string',
        'network' => 'string',
        'amount' => 'float',
        'chain' => 'string',
        'network_fee' => 'string',
        'estimated_time' => 'string',
        'congestion' => 'string',
        'gas_limit' => 'string',
        'gas_price' => 'string',
        'gas_price_gwei' => 'float',
        'estimated_cost' => 'string',
        'sat_per_vb' => 'int',
        'fee_sat' => 'int',
        'lamports' => 'int',
        'fee_tiers' => 'array<string,\OpenAPI\Client\Model\CalculateWalletFee200ResponseDataFeeTiersValue>',
        'gas_spike_warning' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'currency' => null,
        'network' => null,
        'amount' => null,
        'chain' => null,
        'network_fee' => null,
        'estimated_time' => null,
        'congestion' => null,
        'gas_limit' => null,
        'gas_price' => null,
        'gas_price_gwei' => null,
        'estimated_cost' => null,
        'sat_per_vb' => null,
        'fee_sat' => null,
        'lamports' => null,
        'fee_tiers' => null,
        'gas_spike_warning' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'currency' => false,
        'network' => true,
        'amount' => false,
        'chain' => false,
        'network_fee' => false,
        'estimated_time' => false,
        'congestion' => false,
        'gas_limit' => false,
        'gas_price' => false,
        'gas_price_gwei' => false,
        'estimated_cost' => false,
        'sat_per_vb' => false,
        'fee_sat' => false,
        'lamports' => false,
        'fee_tiers' => false,
        'gas_spike_warning' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'currency' => 'currency',
        'network' => 'network',
        'amount' => 'amount',
        'chain' => 'chain',
        'network_fee' => 'networkFee',
        'estimated_time' => 'estimatedTime',
        'congestion' => 'congestion',
        'gas_limit' => 'gasLimit',
        'gas_price' => 'gasPrice',
        'gas_price_gwei' => 'gasPriceGwei',
        'estimated_cost' => 'estimatedCost',
        'sat_per_vb' => 'satPerVb',
        'fee_sat' => 'feeSat',
        'lamports' => 'lamports',
        'fee_tiers' => 'feeTiers',
        'gas_spike_warning' => 'gasSpikeWarning'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'currency' => 'setCurrency',
        'network' => 'setNetwork',
        'amount' => 'setAmount',
        'chain' => 'setChain',
        'network_fee' => 'setNetworkFee',
        'estimated_time' => 'setEstimatedTime',
        'congestion' => 'setCongestion',
        'gas_limit' => 'setGasLimit',
        'gas_price' => 'setGasPrice',
        'gas_price_gwei' => 'setGasPriceGwei',
        'estimated_cost' => 'setEstimatedCost',
        'sat_per_vb' => 'setSatPerVb',
        'fee_sat' => 'setFeeSat',
        'lamports' => 'setLamports',
        'fee_tiers' => 'setFeeTiers',
        'gas_spike_warning' => 'setGasSpikeWarning'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'currency' => 'getCurrency',
        'network' => 'getNetwork',
        'amount' => 'getAmount',
        'chain' => 'getChain',
        'network_fee' => 'getNetworkFee',
        'estimated_time' => 'getEstimatedTime',
        'congestion' => 'getCongestion',
        'gas_limit' => 'getGasLimit',
        'gas_price' => 'getGasPrice',
        'gas_price_gwei' => 'getGasPriceGwei',
        'estimated_cost' => 'getEstimatedCost',
        'sat_per_vb' => 'getSatPerVb',
        'fee_sat' => 'getFeeSat',
        'lamports' => 'getLamports',
        'fee_tiers' => 'getFeeTiers',
        'gas_spike_warning' => 'getGasSpikeWarning'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const CONGESTION_LOW = 'low';
    public const CONGESTION_NORMAL = 'normal';
    public const CONGESTION_HIGH = 'high';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCongestionAllowableValues()
    {
        return [
            self::CONGESTION_LOW,
            self::CONGESTION_NORMAL,
            self::CONGESTION_HIGH,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('network', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('chain', $data ?? [], null);
        $this->setIfExists('network_fee', $data ?? [], null);
        $this->setIfExists('estimated_time', $data ?? [], null);
        $this->setIfExists('congestion', $data ?? [], null);
        $this->setIfExists('gas_limit', $data ?? [], null);
        $this->setIfExists('gas_price', $data ?? [], null);
        $this->setIfExists('gas_price_gwei', $data ?? [], null);
        $this->setIfExists('estimated_cost', $data ?? [], null);
        $this->setIfExists('sat_per_vb', $data ?? [], null);
        $this->setIfExists('fee_sat', $data ?? [], null);
        $this->setIfExists('lamports', $data ?? [], null);
        $this->setIfExists('fee_tiers', $data ?? [], null);
        $this->setIfExists('gas_spike_warning', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getCongestionAllowableValues();
        if (!is_null($this->container['congestion']) && !in_array($this->container['congestion'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'congestion', must be one of '%s'",
                $this->container['congestion'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets currency
     *
     * @return string|null
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param string|null $currency Request currency / native currency for the chain
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets network
     *
     * @return string|null
     */
    public function getNetwork()
    {
        return $this->container['network'];
    }

    /**
     * Sets network
     *
     * @param string|null $network network
     *
     * @return self
     */
    public function setNetwork($network)
    {
        if (is_null($network)) {
            array_push($this->openAPINullablesSetToNull, 'network');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('network', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['network'] = $network;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return float|null
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param float|null $amount amount
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets chain
     *
     * @return string|null
     */
    public function getChain()
    {
        return $this->container['chain'];
    }

    /**
     * Sets chain
     *
     * @param string|null $chain Chain id used for estimation
     *
     * @return self
     */
    public function setChain($chain)
    {
        if (is_null($chain)) {
            throw new \InvalidArgumentException('non-nullable chain cannot be null');
        }
        $this->container['chain'] = $chain;

        return $this;
    }

    /**
     * Gets network_fee
     *
     * @return string|null
     */
    public function getNetworkFee()
    {
        return $this->container['network_fee'];
    }

    /**
     * Sets network_fee
     *
     * @param string|null $network_fee Human-readable network fee from blockchain
     *
     * @return self
     */
    public function setNetworkFee($network_fee)
    {
        if (is_null($network_fee)) {
            throw new \InvalidArgumentException('non-nullable network_fee cannot be null');
        }
        $this->container['network_fee'] = $network_fee;

        return $this;
    }

    /**
     * Gets estimated_time
     *
     * @return string|null
     */
    public function getEstimatedTime()
    {
        return $this->container['estimated_time'];
    }

    /**
     * Sets estimated_time
     *
     * @param string|null $estimated_time estimated_time
     *
     * @return self
     */
    public function setEstimatedTime($estimated_time)
    {
        if (is_null($estimated_time)) {
            throw new \InvalidArgumentException('non-nullable estimated_time cannot be null');
        }
        $this->container['estimated_time'] = $estimated_time;

        return $this;
    }

    /**
     * Gets congestion
     *
     * @return string|null
     */
    public function getCongestion()
    {
        return $this->container['congestion'];
    }

    /**
     * Sets congestion
     *
     * @param string|null $congestion Network congestion level (EVM from gas price; UTXO from sat/vB)
     *
     * @return self
     */
    public function setCongestion($congestion)
    {
        if (is_null($congestion)) {
            throw new \InvalidArgumentException('non-nullable congestion cannot be null');
        }
        $allowedValues = $this->getCongestionAllowableValues();
        if (!in_array($congestion, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'congestion', must be one of '%s'",
                    $congestion,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['congestion'] = $congestion;

        return $this;
    }

    /**
     * Gets gas_limit
     *
     * @return string|null
     */
    public function getGasLimit()
    {
        return $this->container['gas_limit'];
    }

    /**
     * Sets gas_limit
     *
     * @param string|null $gas_limit (EVM only) Gas limit
     *
     * @return self
     */
    public function setGasLimit($gas_limit)
    {
        if (is_null($gas_limit)) {
            throw new \InvalidArgumentException('non-nullable gas_limit cannot be null');
        }
        $this->container['gas_limit'] = $gas_limit;

        return $this;
    }

    /**
     * Gets gas_price
     *
     * @return string|null
     */
    public function getGasPrice()
    {
        return $this->container['gas_price'];
    }

    /**
     * Sets gas_price
     *
     * @param string|null $gas_price (EVM only) Gas price in wei
     *
     * @return self
     */
    public function setGasPrice($gas_price)
    {
        if (is_null($gas_price)) {
            throw new \InvalidArgumentException('non-nullable gas_price cannot be null');
        }
        $this->container['gas_price'] = $gas_price;

        return $this;
    }

    /**
     * Gets gas_price_gwei
     *
     * @return float|null
     */
    public function getGasPriceGwei()
    {
        return $this->container['gas_price_gwei'];
    }

    /**
     * Sets gas_price_gwei
     *
     * @param float|null $gas_price_gwei (EVM only) Gas price in Gwei
     *
     * @return self
     */
    public function setGasPriceGwei($gas_price_gwei)
    {
        if (is_null($gas_price_gwei)) {
            throw new \InvalidArgumentException('non-nullable gas_price_gwei cannot be null');
        }
        $this->container['gas_price_gwei'] = $gas_price_gwei;

        return $this;
    }

    /**
     * Gets estimated_cost
     *
     * @return string|null
     */
    public function getEstimatedCost()
    {
        return $this->container['estimated_cost'];
    }

    /**
     * Sets estimated_cost
     *
     * @param string|null $estimated_cost (EVM only) Cost in wei
     *
     * @return self
     */
    public function setEstimatedCost($estimated_cost)
    {
        if (is_null($estimated_cost)) {
            throw new \InvalidArgumentException('non-nullable estimated_cost cannot be null');
        }
        $this->container['estimated_cost'] = $estimated_cost;

        return $this;
    }

    /**
     * Gets sat_per_vb
     *
     * @return int|null
     */
    public function getSatPerVb()
    {
        return $this->container['sat_per_vb'];
    }

    /**
     * Sets sat_per_vb
     *
     * @param int|null $sat_per_vb (UTXO only) Satoshis per vbyte
     *
     * @return self
     */
    public function setSatPerVb($sat_per_vb)
    {
        if (is_null($sat_per_vb)) {
            throw new \InvalidArgumentException('non-nullable sat_per_vb cannot be null');
        }
        $this->container['sat_per_vb'] = $sat_per_vb;

        return $this;
    }

    /**
     * Gets fee_sat
     *
     * @return int|null
     */
    public function getFeeSat()
    {
        return $this->container['fee_sat'];
    }

    /**
     * Sets fee_sat
     *
     * @param int|null $fee_sat (UTXO only) Fee in satoshis
     *
     * @return self
     */
    public function setFeeSat($fee_sat)
    {
        if (is_null($fee_sat)) {
            throw new \InvalidArgumentException('non-nullable fee_sat cannot be null');
        }
        $this->container['fee_sat'] = $fee_sat;

        return $this;
    }

    /**
     * Gets lamports
     *
     * @return int|null
     */
    public function getLamports()
    {
        return $this->container['lamports'];
    }

    /**
     * Sets lamports
     *
     * @param int|null $lamports (Solana only) Fee in lamports
     *
     * @return self
     */
    public function setLamports($lamports)
    {
        if (is_null($lamports)) {
            throw new \InvalidArgumentException('non-nullable lamports cannot be null');
        }
        $this->container['lamports'] = $lamports;

        return $this;
    }

    /**
     * Gets fee_tiers
     *
     * @return array<string,\OpenAPI\Client\Model\CalculateWalletFee200ResponseDataFeeTiersValue>|null
     */
    public function getFeeTiers()
    {
        return $this->container['fee_tiers'];
    }

    /**
     * Sets fee_tiers
     *
     * @param array<string,\OpenAPI\Client\Model\CalculateWalletFee200ResponseDataFeeTiersValue>|null $fee_tiers (EVM only) slow / normal / fast tiers; each has gasPriceGwei, networkFee
     *
     * @return self
     */
    public function setFeeTiers($fee_tiers)
    {
        if (is_null($fee_tiers)) {
            throw new \InvalidArgumentException('non-nullable fee_tiers cannot be null');
        }
        $this->container['fee_tiers'] = $fee_tiers;

        return $this;
    }

    /**
     * Gets gas_spike_warning
     *
     * @return bool|null
     */
    public function getGasSpikeWarning()
    {
        return $this->container['gas_spike_warning'];
    }

    /**
     * Sets gas_spike_warning
     *
     * @param bool|null $gas_spike_warning True when current gas is ≥5× chain minimum (consider warning user)
     *
     * @return self
     */
    public function setGasSpikeWarning($gas_spike_warning)
    {
        if (is_null($gas_spike_warning)) {
            throw new \InvalidArgumentException('non-nullable gas_spike_warning cannot be null');
        }
        $this->container['gas_spike_warning'] = $gas_spike_warning;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


