<?php
/**
 * GetUserOverview200ResponseFootprint
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API) - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`.
 *
 * The version of the OpenAPI document: 1.3.6
 * Contact: support@mudbase.dev
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * GetUserOverview200ResponseFootprint Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetUserOverview200ResponseFootprint implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'getUserOverview_200_response_footprint';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'file_count' => 'int',
        'storage_used' => 'int',
        'session_count' => 'int',
        'api_key_count' => 'int',
        'collections_in_project' => 'int',
        'collections' => '\OpenAPI\Client\Model\GetOrganizationUsers200ResponseUsersInnerProject[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'file_count' => null,
        'storage_used' => null,
        'session_count' => null,
        'api_key_count' => null,
        'collections_in_project' => null,
        'collections' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'file_count' => false,
        'storage_used' => false,
        'session_count' => false,
        'api_key_count' => false,
        'collections_in_project' => false,
        'collections' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'file_count' => 'fileCount',
        'storage_used' => 'storageUsed',
        'session_count' => 'sessionCount',
        'api_key_count' => 'apiKeyCount',
        'collections_in_project' => 'collectionsInProject',
        'collections' => 'collections'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'file_count' => 'setFileCount',
        'storage_used' => 'setStorageUsed',
        'session_count' => 'setSessionCount',
        'api_key_count' => 'setApiKeyCount',
        'collections_in_project' => 'setCollectionsInProject',
        'collections' => 'setCollections'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'file_count' => 'getFileCount',
        'storage_used' => 'getStorageUsed',
        'session_count' => 'getSessionCount',
        'api_key_count' => 'getApiKeyCount',
        'collections_in_project' => 'getCollectionsInProject',
        'collections' => 'getCollections'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('file_count', $data ?? [], null);
        $this->setIfExists('storage_used', $data ?? [], null);
        $this->setIfExists('session_count', $data ?? [], null);
        $this->setIfExists('api_key_count', $data ?? [], null);
        $this->setIfExists('collections_in_project', $data ?? [], null);
        $this->setIfExists('collections', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets file_count
     *
     * @return int|null
     */
    public function getFileCount()
    {
        return $this->container['file_count'];
    }

    /**
     * Sets file_count
     *
     * @param int|null $file_count file_count
     *
     * @return self
     */
    public function setFileCount($file_count)
    {
        if (is_null($file_count)) {
            throw new \InvalidArgumentException('non-nullable file_count cannot be null');
        }
        $this->container['file_count'] = $file_count;

        return $this;
    }

    /**
     * Gets storage_used
     *
     * @return int|null
     */
    public function getStorageUsed()
    {
        return $this->container['storage_used'];
    }

    /**
     * Sets storage_used
     *
     * @param int|null $storage_used storage_used
     *
     * @return self
     */
    public function setStorageUsed($storage_used)
    {
        if (is_null($storage_used)) {
            throw new \InvalidArgumentException('non-nullable storage_used cannot be null');
        }
        $this->container['storage_used'] = $storage_used;

        return $this;
    }

    /**
     * Gets session_count
     *
     * @return int|null
     */
    public function getSessionCount()
    {
        return $this->container['session_count'];
    }

    /**
     * Sets session_count
     *
     * @param int|null $session_count session_count
     *
     * @return self
     */
    public function setSessionCount($session_count)
    {
        if (is_null($session_count)) {
            throw new \InvalidArgumentException('non-nullable session_count cannot be null');
        }
        $this->container['session_count'] = $session_count;

        return $this;
    }

    /**
     * Gets api_key_count
     *
     * @return int|null
     */
    public function getApiKeyCount()
    {
        return $this->container['api_key_count'];
    }

    /**
     * Sets api_key_count
     *
     * @param int|null $api_key_count api_key_count
     *
     * @return self
     */
    public function setApiKeyCount($api_key_count)
    {
        if (is_null($api_key_count)) {
            throw new \InvalidArgumentException('non-nullable api_key_count cannot be null');
        }
        $this->container['api_key_count'] = $api_key_count;

        return $this;
    }

    /**
     * Gets collections_in_project
     *
     * @return int|null
     */
    public function getCollectionsInProject()
    {
        return $this->container['collections_in_project'];
    }

    /**
     * Sets collections_in_project
     *
     * @param int|null $collections_in_project collections_in_project
     *
     * @return self
     */
    public function setCollectionsInProject($collections_in_project)
    {
        if (is_null($collections_in_project)) {
            throw new \InvalidArgumentException('non-nullable collections_in_project cannot be null');
        }
        $this->container['collections_in_project'] = $collections_in_project;

        return $this;
    }

    /**
     * Gets collections
     *
     * @return \OpenAPI\Client\Model\GetOrganizationUsers200ResponseUsersInnerProject[]|null
     */
    public function getCollections()
    {
        return $this->container['collections'];
    }

    /**
     * Sets collections
     *
     * @param \OpenAPI\Client\Model\GetOrganizationUsers200ResponseUsersInnerProject[]|null $collections collections
     *
     * @return self
     */
    public function setCollections($collections)
    {
        if (is_null($collections)) {
            throw new \InvalidArgumentException('non-nullable collections cannot be null');
        }
        $this->container['collections'] = $collections;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


