<?php
/**
 * MultiRoleUpdateRoleRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MUDBASESDK
 *
 * MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: Flutterwave only for fiat (platform subscriptions + org payment processing with 7% + $0.50 split); crypto payment processor for multi-chain checkout - 📡 Block-based multi-chain wallet monitoring (ETH/UTXO scanners, GetBlock, scanner metrics API)
 *
 * The version of the OpenAPI document: 1.2.8
 * Contact: support@mudbase.dev
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * MultiRoleUpdateRoleRequest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MultiRoleUpdateRoleRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'multiRole_updateRole_request';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'description' => 'string',
        'signup_endpoint' => 'string',
        'requires_approval' => 'bool',
        'requires_payment' => 'bool',
        'requires_kyc' => 'bool',
        'default_permissions' => 'object[]',
        'collection_permissions' => 'array<string,\OpenAPI\Client\Model\MultiRoleUpdateRoleRequestCollectionPermissionsValue>',
        'metadata' => 'object'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => null,
        'description' => null,
        'signup_endpoint' => null,
        'requires_approval' => null,
        'requires_payment' => null,
        'requires_kyc' => null,
        'default_permissions' => null,
        'collection_permissions' => null,
        'metadata' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'name' => false,
        'description' => false,
        'signup_endpoint' => false,
        'requires_approval' => false,
        'requires_payment' => false,
        'requires_kyc' => false,
        'default_permissions' => false,
        'collection_permissions' => false,
        'metadata' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'description' => 'description',
        'signup_endpoint' => 'signupEndpoint',
        'requires_approval' => 'requiresApproval',
        'requires_payment' => 'requiresPayment',
        'requires_kyc' => 'requiresKYC',
        'default_permissions' => 'defaultPermissions',
        'collection_permissions' => 'collectionPermissions',
        'metadata' => 'metadata'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'description' => 'setDescription',
        'signup_endpoint' => 'setSignupEndpoint',
        'requires_approval' => 'setRequiresApproval',
        'requires_payment' => 'setRequiresPayment',
        'requires_kyc' => 'setRequiresKyc',
        'default_permissions' => 'setDefaultPermissions',
        'collection_permissions' => 'setCollectionPermissions',
        'metadata' => 'setMetadata'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'description' => 'getDescription',
        'signup_endpoint' => 'getSignupEndpoint',
        'requires_approval' => 'getRequiresApproval',
        'requires_payment' => 'getRequiresPayment',
        'requires_kyc' => 'getRequiresKyc',
        'default_permissions' => 'getDefaultPermissions',
        'collection_permissions' => 'getCollectionPermissions',
        'metadata' => 'getMetadata'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('signup_endpoint', $data ?? [], null);
        $this->setIfExists('requires_approval', $data ?? [], null);
        $this->setIfExists('requires_payment', $data ?? [], null);
        $this->setIfExists('requires_kyc', $data ?? [], null);
        $this->setIfExists('default_permissions', $data ?? [], null);
        $this->setIfExists('collection_permissions', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets signup_endpoint
     *
     * @return string|null
     */
    public function getSignupEndpoint()
    {
        return $this->container['signup_endpoint'];
    }

    /**
     * Sets signup_endpoint
     *
     * @param string|null $signup_endpoint signup_endpoint
     *
     * @return self
     */
    public function setSignupEndpoint($signup_endpoint)
    {
        if (is_null($signup_endpoint)) {
            throw new \InvalidArgumentException('non-nullable signup_endpoint cannot be null');
        }
        $this->container['signup_endpoint'] = $signup_endpoint;

        return $this;
    }

    /**
     * Gets requires_approval
     *
     * @return bool|null
     */
    public function getRequiresApproval()
    {
        return $this->container['requires_approval'];
    }

    /**
     * Sets requires_approval
     *
     * @param bool|null $requires_approval requires_approval
     *
     * @return self
     */
    public function setRequiresApproval($requires_approval)
    {
        if (is_null($requires_approval)) {
            throw new \InvalidArgumentException('non-nullable requires_approval cannot be null');
        }
        $this->container['requires_approval'] = $requires_approval;

        return $this;
    }

    /**
     * Gets requires_payment
     *
     * @return bool|null
     */
    public function getRequiresPayment()
    {
        return $this->container['requires_payment'];
    }

    /**
     * Sets requires_payment
     *
     * @param bool|null $requires_payment requires_payment
     *
     * @return self
     */
    public function setRequiresPayment($requires_payment)
    {
        if (is_null($requires_payment)) {
            throw new \InvalidArgumentException('non-nullable requires_payment cannot be null');
        }
        $this->container['requires_payment'] = $requires_payment;

        return $this;
    }

    /**
     * Gets requires_kyc
     *
     * @return bool|null
     */
    public function getRequiresKyc()
    {
        return $this->container['requires_kyc'];
    }

    /**
     * Sets requires_kyc
     *
     * @param bool|null $requires_kyc requires_kyc
     *
     * @return self
     */
    public function setRequiresKyc($requires_kyc)
    {
        if (is_null($requires_kyc)) {
            throw new \InvalidArgumentException('non-nullable requires_kyc cannot be null');
        }
        $this->container['requires_kyc'] = $requires_kyc;

        return $this;
    }

    /**
     * Gets default_permissions
     *
     * @return object[]|null
     */
    public function getDefaultPermissions()
    {
        return $this->container['default_permissions'];
    }

    /**
     * Sets default_permissions
     *
     * @param object[]|null $default_permissions default_permissions
     *
     * @return self
     */
    public function setDefaultPermissions($default_permissions)
    {
        if (is_null($default_permissions)) {
            throw new \InvalidArgumentException('non-nullable default_permissions cannot be null');
        }
        $this->container['default_permissions'] = $default_permissions;

        return $this;
    }

    /**
     * Gets collection_permissions
     *
     * @return array<string,\OpenAPI\Client\Model\MultiRoleUpdateRoleRequestCollectionPermissionsValue>|null
     */
    public function getCollectionPermissions()
    {
        return $this->container['collection_permissions'];
    }

    /**
     * Sets collection_permissions
     *
     * @param array<string,\OpenAPI\Client\Model\MultiRoleUpdateRoleRequestCollectionPermissionsValue>|null $collection_permissions Per-collection CRUD map (same as POST add role).
     *
     * @return self
     */
    public function setCollectionPermissions($collection_permissions)
    {
        if (is_null($collection_permissions)) {
            throw new \InvalidArgumentException('non-nullable collection_permissions cannot be null');
        }
        $this->container['collection_permissions'] = $collection_permissions;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return object|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param object|null $metadata metadata
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            throw new \InvalidArgumentException('non-nullable metadata cannot be null');
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


